providers = ["python"]

[start]
cmd = "cd backend && python manage.py migrate && gunicorn rajbari_ride.wsgi --bind 0.0.0.0:${PORT:-8000}"

[build]
cmds = ["pip install -r requirements.txt", "cd backend && python manage.py collectstatic --noinput"]
