[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install -r ../requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "cd backend && python manage.py migrate && daphne -b 0.0.0.0 -p $PORT rajbari_ride.asgi:application"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
